services:
  - type: web
    name: trading-bot-ultra
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python pro_market_bot_ultra_fixed.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
